Adding new index and Dockerfile
lilab-bcb/cumulus pull request #353
Opened 2022-08-10 18:03 UTC by jshleap

Adding Version 2.0.0 of space ranger as well as index human_probe_v2

2022-08-10 22:16 UTC, yihming requested changes

2022-08-10 22:16 UTC, yihming commented on docker/spaceranger/2.0.0/Dockerfile
> +ENV PATH=/software:/software/spaceranger-1.3.1:$PATH
Should `spaceranger-1.3.1` be changed to `spaceranger-2.0.0`? You'll need to check if the path is correct by entering a docker container running this image.

2022-08-10 22:16 UTC, yihming commented on workflows/cellranger/index.tsv
> +human_probe_v2  gs://regev-lab/resources/cellranger/Visium_Human_Transcriptome_Probe_Set_v2.0_GRCh38-2020-A.csv
You may want to add a newline at the end, in case the parse doesn't recognize the last line correctly.

2022-08-10 22:16 UTC, yihming commented on docker/spaceranger/2.0.0/Dockerfile
> +ADD https://raw.githubusercontent.com/klarman-cell-observatory/cumulus/master/docker/monitor_script.sh /software
Change to `https://raw.githubusercontent.com/lilab-bcb/cumulus/master/docker/monitor_script.sh`.

2022-08-11 13:09 UTC, jshleap commented
Docker tested locally:
`root@0e12433cd44e:/# spaceranger --help
spaceranger spaceranger-2.0.0
Process 10x Genomics Spatial Gene Expression data

USAGE:
    spaceranger <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    count               Count gene expression and feature barcoding reads from a single capture area
    aggr                Aggregate data from multiple 'spaceranger count' runs
    targeted-compare    Analyze targeted enrichment performance by comparing a targeted sample to its cognate parent WTA sample (used as input for
                        targeted gene expression)
    targeted-depth      Estimate targeted read depth values (mean reads per spot) for a specified input parent WTA sample and a target panel CSV file
    mkfastq             Run Illumina demultiplexer on sample sheets that contain 10x-specific sample index sets
    testrun             Execute the 'count' pipeline on a small test dataset
    mat2csv             Convert a gene count matrix to CSV format
    mkref               Prepare a reference for use with 10x analysis software. Requires a GTF and FASTA
    mkgtf               Filter a GTF file by attribute prior to creating a 10x reference
    upload              Upload analysis logs to 10x Genomics support
    sitecheck           Collect linux system configuration information
    help                Print this message or the help of the given subcommand(s)`

2022-08-11 13:10 UTC, jshleap commented
Pushed to dockerhub

2022-08-11 13:18 UTC, jshleap commented
Pushed to Quay

2022-08-12 03:59 UTC, yihming approved these changes

2022-08-12 04:01 UTC, merged